name: "Flagsmith Feature Flag Remover"
description: "Remove unused flags based on config file in repository"
inputs:
  access_token:
    description: "Access token to get github file action, github token"
    required: true
    default: "${{ github.TOKEN }}"
  apitokenflagsmith:
    description: "API token to call the Flagsmith API"
    required: true
  flagsmithprojectid:
    description: "Project id from the Flagsmith repository"
    required: true
  ownerrepo:
    description: "Github organization name"
    required: true
    default: "${{ github.GITHUB_REPOSITORY }}"
  path:
    description: "Path to the file in the repo to run the diff"
    required: true
  ref:
    description: "The specific branch where the config file lives"
    required: true
  sendmessage:
    description: "Activate when you want to sent a message to slack"
    required: false
  slackwebhook:
    description: "Provide the slack webhook key"
    required: false
  dryrun:
    description: "When having dry run = true, only message will be sent be nothing will be removed"
    required: true
branding:
  icon: "message-circle"
  color: "white"
runs:
  using: "node16"
  main: "dist/index.js"
