name: "units-test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arrays:
          [
            {
              "ref": "production-careshop",
              "sourcepath": "apps/careshop/src/config/flagsmithConfig.ts",
              "flagsmithProjectId": "7064",
            },
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          access_token: ${{ secrets.GITHUB }}
          apitokenflagsmith: ${{ secrets.APITOKENFLAGSMITH }}

          owner: "AlphaFounders"
          repo: "sales-crm-frontend"

          flagsmithprojectid: ${{ matrix.arrays.flagsmithProjectId }}
          path: ${{ matrix.arrays.sourcepath }}
          ref: ${{ matrix.arrays.ref }}
