name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: |
          echo ${{ env }}
          echo ${{ vars }}
          echo ${{ env.apitokenflagsmith }}
          echo ${{ github.token }}
          echo ${{ env.flagsmithUrl }}
          echo ${{ env.apitokenflagsmith }}
          echo ${{ env.path }}

      - uses: actions/checkout@v3
      - uses: ./
        with:
          access_token: ${{ github.token }}
          flagsmithUrl: ${{ env.flagsmithUrl }}
          apitokenflagsmith: ${{ env.apitokenflagsmith }}
          owner: "AlphaFounders"
          repo: "sales-crm-frontend"
          path: ${{ env.path }}
